create table phone (id integer generated by default as identity, created timestamp not null, modified timestamp not null, citycode varchar(3), contrycode varchar(3) not null, number varchar(10) not null, userid varchar(36), primary key (id))
create table users (id varchar(36) not null, created timestamp not null, modified timestamp not null, email varchar(100) not null, is_active boolean not null, last_login timestamp not null, name varchar(50) not null, password varchar(100) not null, token varchar(255), username varchar(55) not null, primary key (id))
alter table users drop constraint if exists UK_6dotkott2kjsp8vw4d0m25fb7
alter table users add constraint UK_6dotkott2kjsp8vw4d0m25fb7 unique (email)
alter table users drop constraint if exists UK_r43af9ap4edm43mmtq01oddj6
alter table users add constraint UK_r43af9ap4edm43mmtq01oddj6 unique (username)
alter table phone add constraint FKaveov263ofm970bc3f2nh5010 foreign key (userid) references users